engine:
  mode: dry_run  # dry_run or live
  max_positions: 3

solana:
  rpc_url: https://api.mainnet-beta.solana.com
  ws_url: wss://api.mainnet-beta.solana.com
  network: mainnet-beta  # mainnet-beta, devnet, or testnet
  wallet_path: wallet.json
  jupiter_api_url: https://quote-api.jup.ag/v6

listener:
  enabled: true
  mode: websocket  # "websocket" (default, free with rate limits) or "polling" (fallback)
  polling_interval_sec: 10  # How often to poll RPC (only used in polling mode)
  programs:
    - "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"  # Raydium AMM
    - "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP"  # Orca Whirlpool
  coalesce_window_ms: 200  # Deduplicate events within this window

trading:
  base_mint: SOL
  quote_mint: USDC
  max_spend_per_trade: 0.5  # SOL amount per trade
  max_open_positions: 3
  slippage_bps: 150  # 1.5%
  priority_fee_microlamports: 5000

rules:
  min_liquidity_usd: 20000
  max_mint_age_sec: 7200  # 2 hours
  min_holders: 200
  dev_wallet_max_pct: 20  # Max % tokens in dev wallet
  block_freeze_authority: true  # Block tokens with freeze authority
  allow_mint_authority: false  # Block tokens with mint authority

risk:
  stop_loss_pct: 10  # Sell if 10% loss
  take_profit_pct: 10  # Sell if 10% profit
  max_trade_duration_sec: 600  # 10 minutes - force exit to avoid rugpull
